-- -- 1. 初始化环境与自定义类型
-- DO
-- $$
-- BEGIN
--     IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'uint256') THEN
-- CREATE DOMAIN UINT256 AS NUMERIC CHECK (VALUE >= 0 AND VALUE < POWER(CAST(2 AS NUMERIC), CAST(256 AS NUMERIC)) AND SCALE(VALUE) = 0);
-- END IF;
-- END
-- $$;
--
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp" CASCADE;
--
-- -- 2. Events 表 (父事件)
-- CREATE TABLE IF NOT EXISTS events (
--     guid          TEXT PRIMARY KEY DEFAULT replace(uuid_generate_v4()::text, '-', ''),
--     title         TEXT NOT NULL,
--     description   TEXT,
--     image_url     TEXT,
--     start_date    INTEGER,                     -- Unix 时间戳
--     end_date      INTEGER,                     -- Unix 时间戳
--     is_active     BOOLEAN DEFAULT TRUE,
--     created       INTEGER CHECK (created > 0),
--     updated       INTEGER CHECK (updated > 0)
--     );
-- CREATE INDEX IF NOT EXISTS events_is_active ON events(is_active);
-- CREATE INDEX IF NOT EXISTS events_end_date ON events(end_date);
--
--
-- -- 3. Sub_Events 表 (具体的预测市场)
-- CREATE TABLE IF NOT EXISTS sub_events (
--     guid                 TEXT PRIMARY KEY DEFAULT replace(uuid_generate_v4()::text, '-', ''),
--     event_guid           TEXT NOT NULL REFERENCES events(guid) ON DELETE CASCADE,
--     question             TEXT NOT NULL,
--     description          TEXT,
--     status               VARCHAR(20) DEFAULT 'ACTIVE',
--
--     -- 结果字段 (注意：由于循环依赖，外键约束在脚本末尾添加)
--     winning_outcome_guid TEXT,
--
--     resolution_date      INTEGER,
--     resolution_source    TEXT,
--
--     -- 预留链上字段
--     condition_id         VARCHAR(66),
--     created              INTEGER CHECK (created > 0),
--     updated              INTEGER CHECK (updated > 0)
--     );
-- CREATE INDEX IF NOT EXISTS sub_events_event_guid ON sub_events(event_guid);
-- CREATE INDEX IF NOT EXISTS sub_events_status ON sub_events(status);
--
--
-- -- 4. Outcomes 表 (下注选项)
-- CREATE TABLE IF NOT EXISTS outcomes (
--     guid              TEXT PRIMARY KEY DEFAULT replace(uuid_generate_v4()::text, '-', ''),
--     sub_event_guid    TEXT NOT NULL REFERENCES sub_events(guid) ON DELETE CASCADE,
--     name              VARCHAR(100) NOT NULL,
--     color             VARCHAR(20),
--     idx               INTEGER DEFAULT 0,  -- 选项排序，从0开始 比如yes=0, no=1
--
--     -- 交易相关
--     current_price     NUMERIC(5, 4) DEFAULT 0.5,
--     clob_token_id     UINT256,                 -- 使用脚本开头的 UINT256 类型
--
--     created           INTEGER CHECK (created > 0),
--     updated           INTEGER CHECK (updated > 0)
--     );
-- CREATE INDEX IF NOT EXISTS outcomes_sub_event_guid ON outcomes(sub_event_guid);
-- CREATE INDEX IF NOT EXISTS outcomes_clob_token_id ON outcomes(clob_token_id);
--
--
-- -- 5. 解决循环依赖：补上子事件结果的外键约束
-- DO $$
-- BEGIN
--     IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_sub_events_winning_outcome') THEN
-- ALTER TABLE sub_events
--     ADD CONSTRAINT fk_sub_events_winning_outcome
--         FOREIGN KEY (winning_outcome_guid)
--             REFERENCES outcomes(guid)
--             ON DELETE SET NULL;
-- END IF;
-- END $$;
--
--
-- -- 6. Tags 表 (标签)
-- CREATE TABLE IF NOT EXISTS tags (
--     guid       TEXT PRIMARY KEY DEFAULT replace(uuid_generate_v4()::text, '-', ''),
--     name       VARCHAR(100) NOT NULL UNIQUE,
--     created    INTEGER CHECK (created > 0),
--     updated    INTEGER CHECK (updated > 0)
--     );
--
--
-- -- 7. Event_Tags 表 (关联表)
-- CREATE TABLE IF NOT EXISTS event_tags (
--     id         SERIAL PRIMARY KEY,
--     event_guid TEXT NOT NULL REFERENCES events(guid) ON DELETE CASCADE,
--     tag_guid   TEXT NOT NULL REFERENCES tags(guid) ON DELETE CASCADE,
--     created    INTEGER CHECK (created > 0),
--     UNIQUE(event_guid, tag_guid)
-- );
-- CREATE INDEX IF NOT EXISTS event_tags_event_guid ON event_tags(event_guid);
-- CREATE INDEX IF NOT EXISTS event_tags_tag_guid ON event_tags(tag_guid);